apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
rules:
  - apiGroups: [""]
    resources: 
      - pods
      - nodes
      - namespaces
      - services
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
      - resourcequotas
      - limitranges
      - secrets
      - configmaps
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: 
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: ["list", "watch"]
  - apiGroups: ["batch"]
    resources: 
      - cronjobs
      - jobs
    verbs: ["list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: 
      - horizontalpodautoscalers
    verbs: ["list", "watch"]
  - apiGroups: ["policy"]
    resources: 
      - poddisruptionbudgets
    verbs: ["list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: 
      - networkpolicies
      - ingresses
    verbs: ["list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: 
      - storageclasses
      - csinodes
      - csistoragecapacities
      - volumeattachments
    verbs: ["list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: 
      - leases
    verbs: ["list", "watch"]
