apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oris-predictive-autoscaler

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: kube-state-metrics
  app.kubernetes.io/component: monitoring
