apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: oris-predictive-autoscaler
  labels:
    app: kube-state-metrics
spec:
  type: ClusterIP
  selector:
    app: kube-state-metrics
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
