apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oris-predictive-autoscaler

resources:
  - rabbitmq
  - kafka
  - kafdrop

commonLabels:
  app.kubernetes.io/part-of: messaging
