apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oris-predictive-autoscaler

resources:
  - configmap-datasources.yaml
  - configmap-dashboard-providers.yaml
  - configmap-dashboards.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/component: monitoring
