apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: oris-predictive-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:12.1.1
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboard-providers
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboard-providers
        configMap:
          name: grafana-dashboard-providers
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: oris-predictive-autoscaler
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: oris-predictive-autoscaler
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      isDefault: true
      access: proxy
      editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: oris-predictive-autoscaler
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: oris-predictive-autoscaler
data:
  rabbitmq-dashboard.json: |
      {
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": {
                "type": "datasource",
                "uid": "grafana"
              },
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 0,
        "id": 1,
        "links": [],
        "panels": [
          {
            "datasource": {
              "type": "prometheus",
              "uid": "PBFA97CFB590B2093"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "fixedColor": "red",
                  "mode": "palette-classic",
                  "seriesBy": "max"
                },
                "custom": {
                  "axisBorderShow": true,
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisLabel": "Message/s",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "barWidthFactor": 0.6,
                  "drawStyle": "line",
                  "fillOpacity": 12,
                  "gradientMode": "opacity",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "insertNulls": false,
                  "lineInterpolation": "smooth",
                  "lineWidth": 2,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "auto",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "percentage",
                  "steps": [
                    {
                      "color": "green",
                      "value": 0
                    }
                  ]
                }
              },
              "overrides": [
                {
                  "matcher": {
                    "id": "byName",
                    "options": "Rejected"
                  },
                  "properties": [
                    {
                      "id": "color",
                      "value": {
                        "fixedColor": "red",
                        "mode": "fixed"
                      }
                    }
                  ]
                },
                {
                  "matcher": {
                    "id": "byName",
                    "options": "Arrived"
                  },
                  "properties": [
                    {
                      "id": "color",
                      "value": {
                        "fixedColor": "green",
                        "mode": "fixed"
                      }
                    }
                  ]
                }
              ]
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            },
            "id": 3,
            "interval": "1",
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "hideZeros": false,
                "mode": "single",
                "sort": "none"
              }
            },
            "pluginVersion": "12.1.1",
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "disableTextWrap": false,
                "editorMode": "builder",
                "expr": "rate(rabbitmq_global_messages_received_total[10s])",
                "fullMetaSearch": false,
                "includeNullMetadata": false,
                "legendFormat": "Arrived",
                "range": true,
                "refId": "A",
                "useBackend": false
              },
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "disableTextWrap": false,
                "editorMode": "builder",
                "expr": "sum(rate(rabbitmq_global_messages_dead_lettered_maxlen_total[10s]))",
                "fullMetaSearch": false,
                "hide": false,
                "includeNullMetadata": false,
                "instant": false,
                "legendFormat": "Rejected",
                "range": true,
                "refId": "B",
                "useBackend": false
              }
            ],
            "title": "Queue Metrics",
            "transparent": true,
            "type": "timeseries"
          },
          {
            "datasource": {
              "type": "prometheus",
              "uid": "PBFA97CFB590B2093"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": 0
                    }
                  ]
                }
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 0
            },
            "id": 4,
            "interval": "1h",
            "options": {
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto",
              "orientation": "auto",
              "percentChangeColorMode": "standard",
              "reduceOptions": {
                "calcs": [
                  "lastNotNull"
                ],
                "fields": "",
                "values": false
              },
              "showPercentChange": false,
              "textMode": "auto",
              "wideLayout": true
            },
            "pluginVersion": "12.1.1",
            "targets": [
              {
                "disableTextWrap": false,
                "editorMode": "builder",
                "exemplar": false,
                "expr": "max_over_time(rabbitmq_global_messages_received_total[$__interval]) - (min_over_time(rabbitmq_global_messages_received_total[$__interval]))",
                "fullMetaSearch": false,
                "includeNullMetadata": true,
                "instant": true,
                "interval": "",
                "legendFormat": "__auto",
                "range": false,
                "refId": "A",
                "useBackend": false
              }
            ],
            "title": "Total Messages (Last Hour)",
            "type": "stat"
          },
          {
            "datasource": {
              "type": "prometheus",
              "uid": "PBFA97CFB590B2093"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "axisBorderShow": false,
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "barWidthFactor": 0.6,
                  "drawStyle": "line",
                  "fillOpacity": 0,
                  "gradientMode": "none",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "insertNulls": false,
                  "lineInterpolation": "linear",
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "auto",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": 0
                    }
                  ]
                }
              },
              "overrides": [
                {
                  "__systemRef": "hideSeriesFrom",
                  "matcher": {
                    "id": "byNames",
                    "options": {
                      "mode": "exclude",
                      "names": [
                        "Rejection Rate"
                      ],
                      "prefix": "All except:",
                      "readOnly": true
                    }
                  },
                  "properties": [
                    {
                      "id": "custom.hideFrom",
                      "value": {
                        "legend": false,
                        "tooltip": false,
                        "viz": true
                      }
                    }
                  ]
                },
                {
                  "matcher": {
                    "id": "byName",
                    "options": "Rejection Rate"
                  },
                  "properties": [
                    {
                      "id": "color",
                      "value": {
                        "fixedColor": "red",
                        "mode": "fixed"
                      }
                    }
                  ]
                }
              ]
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 8
            },
            "id": 5,
            "interval": "5",
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "hideZeros": false,
                "mode": "single",
                "sort": "none"
              }
            },
            "pluginVersion": "12.1.1",
            "targets": [
              {
                "disableTextWrap": false,
                "editorMode": "builder",
                "expr": "sum(rate(rabbitmq_global_messages_dead_lettered_maxlen_total[$__interval])) / (sum(rate(rabbitmq_global_messages_received_total[$__interval])) + 0.001)",
                "fullMetaSearch": false,
                "includeNullMetadata": false,
                "legendFormat": "Rejection Rate",
                "range": true,
                "refId": "A",
                "useBackend": false
              }
            ],
            "title": "Rejection Rate",
            "type": "timeseries"
          },
          {
            "datasource": {
              "type": "prometheus",
              "uid": "PBFA97CFB590B2093"
            },
            "description": "",
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": 0
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                }
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 12,
              "y": 8
            },
            "id": 6,
            "options": {
              "colorMode": "value",
              "graphMode": "none",
              "justifyMode": "auto",
              "orientation": "auto",
              "percentChangeColorMode": "standard",
              "reduceOptions": {
                "calcs": [
                  "lastNotNull"
                ],
                "fields": "",
                "values": false
              },
              "showPercentChange": false,
              "textMode": "auto",
              "wideLayout": true
            },
            "pluginVersion": "12.1.1",
            "targets": [
              {
                "disableTextWrap": false,
                "editorMode": "builder",
                "expr": "sum(kube_deployment_status_replicas_available{deployment=\"python-service\"})",
                "fullMetaSearch": false,
                "includeNullMetadata": true,
                "legendFormat": "__auto",
                "range": true,
                "refId": "A",
                "useBackend": false
              }
            ],
            "title": "Active Replicas (Services)",
            "type": "stat"
          },
          {
            "datasource": {
              "type": "prometheus",
              "uid": "PBFA97CFB590B2093"
            },
            "description": "",
            "fieldConfig": {
              "defaults": {
                "color": {
                  "fixedColor": "blue",
                  "mode": "fixed"
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": 0
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                }
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 18,
              "y": 8
            },
            "id": 7,
            "options": {
              "colorMode": "value",
              "graphMode": "none",
              "justifyMode": "auto",
              "orientation": "auto",
              "percentChangeColorMode": "standard",
              "reduceOptions": {
                "calcs": [
                  "lastNotNull"
                ],
                "fields": "",
                "values": false
              },
              "showPercentChange": false,
              "textMode": "auto",
              "wideLayout": true
            },
            "pluginVersion": "12.1.1",
            "targets": [
              {
                "disableTextWrap": false,
                "editorMode": "builder",
                "expr": "kube_deployment_status_replicas{deployment=\"python-service\", namespace=\"oris-predictive-autoscaler\"}",
                "fullMetaSearch": false,
                "includeNullMetadata": true,
                "legendFormat": "__auto",
                "range": true,
                "refId": "A",
                "useBackend": false
              }
            ],
            "title": "Prescribed Replicas (Service)",
            "type": "stat"
          }
        ],
        "preload": false,
        "refresh": "5s",
        "schemaVersion": 41,
        "tags": [
          "rabbitmq",
          "prometheus"
        ],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now-5m",
          "to": "now"
        },
        "timepicker": {},
        "timezone": "",
        "title": "RabbitMQ-Overview",
        "uid": "rabbitmq-overview",
        "version": 2
      }