apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: oris-predictive-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:12.1.1
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        env:  # Aggiungi questa sezione
        - name: GF_DASHBOARDS_MIN_REFRESH_INTERVAL
          value: "1s"  # O "500ms" per mezzo secondo

      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: oris-predictive-autoscaler
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: oris-predictive-autoscaler
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      isDefault: true
      access: proxy
      editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: oris-predictive-autoscaler
data:
  rabbitmq-dashboard.json: |
    {
      "__inputs": [
        {
          "name": "DS_PROMETHEUS",
          "label": "Prometheus",
          "description": "",
          "type": "datasource",
          "pluginId": "prometheus",
          "pluginName": "Prometheus"
        }
      ],
      "__requires": [
        {
          "type": "grafana",
          "id": "grafana",
          "name": "Grafana",
          "version": "6.2.5"
        },
        {
          "type": "panel",
          "id": "graph",
          "name": "Graph",
          "version": ""
        },
        {
          "type": "datasource",
          "id": "prometheus",
          "name": "Prometheus",
          "version": "1.0.0"
        },
        {
          "type": "panel",
          "id": "singlestat",
          "name": "Singlestat",
          "version": ""
        }
      ],
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": 10991,
      "graphTooltip": 0,
      "id": null,
      "iteration": 1578659999129,
      "links": [],
      "panels": [
        {
          "id": 1,
          "type": "timeseries",
          "title": "Arrivi (publish rate)",
          "datasource": "Prometheus",
          "gridPos": {"h": 9, "w": 12, "x": 0, "y": 0},
          "targets": [
            {
              "expr": "sum(rate(rabbitmq_queue_messages_published_total[1m]))",
              "legendFormat": "tutte le code",
              "interval": ""
            }
          ],
          "fieldConfig": {"defaults": {"unit": "ops"}},
          "options": {"legend": {"displayMode": "list", "placement": "bottom"}}
        },
        {
          "id": 2,
            "type": "stat",
            "title": "Messaggi pubblicati (totale)",
            "datasource": "Prometheus",
            "gridPos": {"h": 4, "w": 6, "x": 12, "y": 0},
            "targets": [
              {
                "expr": "sum(rabbitmq_queue_messages_published_total)",
                "legendFormat": "totale"
              }
            ],
            "options": {"reduceOptions": {"calcs": ["lastNotNull"]}, "orientation": "horizontal"},
            "fieldConfig": {"defaults": {"unit": "none"}}
        }
      ],
      "refresh": "10s",
      "schemaVersion": 21,
      "style": "dark",
      "tags": [
        "rabbitmq",
        "prometheus"
      ],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-5m",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ],
        "time_options": [
          "5m",
          "15m",
          "1h",
          "6h",
          "12h",
          "24h",
          "2d",
          "7d",
          "30d"
        ]
      },
      "timezone": "",
      "title": "RabbitMQ-Overview",
      "uid": "rabbitmq-overview",
      "version": 3
    }
  rabbitmq-dashboard.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/provisioning/dashboards/rabbitmq-dashboard.json
