{
 "title": "RabbitMQ-Overview",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rabbitmq_global_messages_received_total[10s])",
     "legendFormat": "Arrived"
    },
    {
     "expr": "sum(rate(rabbitmq_global_messages_dead_lettered_maxlen_total[10s]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Total Messages (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(rabbitmq_global_messages_received_total[$__interval]) - (min_over_time(rabbitmq_global_messages_received_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejection Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_dead_lettered_maxlen_total[$__interval])) / (sum(rate(rabbitmq_global_messages_received_total[$__interval])) + 0.001)",
     "legendFormat": "Rejection Rate"
    }
   ]
  },
  {
   "title": "Active Replicas (Services)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=\"python-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pods Instanciated (Services)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"oris-predictive-autoscaler\", pod=~\"python-service.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prescribed Replicas (Service)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"python-service\", namespace=\"oris-predictive-autoscaler\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}