apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: oris-predictive-autoscaler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# ConfigMap con le definizioni per creare la coda "message-queue" limitata a 100 messaggi
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-definitions
  namespace: oris-predictive-autoscaler
data:
  definitions.json: |
    {
      "vhosts": [
        { "name": "/" }
      ],
      "queues": [
        {
          "name": "message-queue",
          "vhost": "/",
          "arguments": {
            "x-max-length": 100
          }
        }
      ],
      "users": [
        {
          "name": "admin",
          "password": "password",
          "tags": ["administrator"]
        }
      ],
      "permissions": [
        {
          "user": "admin",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ]
    }
---
# ConfigMap per configurazione RabbitMQ: carica le definizioni al bootstrap
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: oris-predictive-autoscaler
data:
  rabbitmq.conf: |
    # Indica al management plugin di importare il file delle definizioni
    management.load_definitions = /etc/rabbitmq/definitions.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: oris-predictive-autoscaler
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "admin"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-definitions
          mountPath: /etc/rabbitmq/definitions.json
          subPath: definitions.json
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
      - name: rabbitmq-definitions
        configMap:
          name: rabbitmq-definitions
      - name: rabbitmq-config
        configMap:
          name: rabbitmq-config
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: oris-predictive-autoscaler
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management
  selector:
    app: rabbitmq
