apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: oris-predictive-autoscaler
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
