apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-service-cpu
  namespace: oris-predictive-autoscaler
  labels:
    app: python-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
