apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: oris-predictive-autoscaler
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
              name: http
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka-service:9092,kafka-service:9092"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
