apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: oris-predictive-autoscaler
  labels:
    app: kafdrop
spec:
  type: ClusterIP
  selector:
    app: kafdrop
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
