apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: oris-predictive-autoscaler
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 1s
    
    scrape_configs:
      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq-service:15692']

      - job_name: 'k6-metrics'
        static_configs:
          - targets: ['host.docker.internal:6565']
        metrics_path: /metrics
        scrape_interval: 5s
      
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:8080']
        scrape_interval: 1s
