apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: oris-predictive-autoscaler
  labels:
    app: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
