apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: oris-predictive-autoscaler
  labels:
    app: prometheus-adapter
data:
  config.yaml: |
    externalRules:
    - seriesQuery: '{__name__=~"rabbitmq_global_messages_dead_lettered_maxlen_total|rabbitmq_global_messages_received_total"}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
      name:
        matches: "^.*"
        as: "rejection_rate"
      metricsQuery: 'sum(rate(rabbitmq_global_messages_dead_lettered_maxlen_total[5s])) / (sum(rate(rabbitmq_global_messages_received_total[5s])) + 0.001)'
