apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oris-predictive-autoscaler

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - rolebinding.yaml
  - deployment.yaml
  - service.yaml
  - apiservice.yaml

commonLabels:
  app.kubernetes.io/name: prometheus-adapter
  app.kubernetes.io/component: autoscaling
