apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  namespace: oris-predictive-autoscaler
  labels:
    app: prometheus-adapter
spec:
  type: ClusterIP
  ports:
  - port: 443
    protocol: TCP
    targetPort: https
    name: https
  selector:
    app: prometheus-adapter
